NAME= PmergeMe

CXX= c++

CXXFLAGS= -Wall -Wextra -Werror -g -std=c++98

SRC = src/main.cpp src/PmergeMe.cpp src/PmergeMeDeque.cpp src/PmergeMeVector.cpp

OBJ = $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -f $(OBJ)
	
fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re